name: "Deploy NextJS VPS Hostinger"
on:
  push:
    branches:
      - main

jobs:
  build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Executar git pull no servidor
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /projects
            echo "PWD inicial:"
            pwd
            echo "Conteúdo de /projects:"
            ls -la /root/projects

            if [ ! -d "/root/projects/fullstack-quiz/.git" ]; then
                echo "Clonando repositório..."
                git clone https://github.com/jnerydesigner/fullstack-quiz.git /root/projects/fullstack-quiz
            else
                echo "Repositório já clonado"
            fi

            echo "Entrando na pasta do projeto"
            cd /root/projects/fullstack-quiz
            echo "PWD após cd:"
            pwd
            echo "Conteúdo da pasta do projeto:"
            ls -la

            echo "Executando git pull"
            git pull origin main

      - name: Instalar as dependencias Front e Back
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/projects/fullstack-quiz/quiz-fullstack
            yarn install
            cd /root/projects/fullstack-quiz/backend-quiz
            yarn install

      - name: Executar o Build No Servidor
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/projects/fullstack-quiz/quiz-fullstack
            yarn build
            cd /root/projects/fullstack-quiz/backend-quiz
            yarn build

      - name: Executar o PM2 e Start No Servidor
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/projects/fullstack-quiz/backend-quiz
            pm2 update backend-quiz || true
            pm2 start my-pm2-start.json --update-env || pm2 restart my-pm2-start.json

            cd /root/projects/fullstack-quiz/quiz-fullstack
            pm2 update fullstack-quiz || true
            pm2 start my-pm2-start.json --update-env || pm2 restart my-pm2-start.json
